# Based off segment.io's script:
# https://github.com/segmentio/eslint-config/blob/master/.circleci/config.yml

version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Login to npm
          command: npm config set "//registry.npmjs.org/:_authToken" $NPM_TOKEN
      - run:
          name: Publish to npm
          command: npm publish .
workflows:
  version: 2
  publish:
    jobs:
      - publish:
          context: oneflow
          filters:
            tags:
              # Not a super sophisticated check, but it works with e.g. `v1.0.0-alpha.1`
              only: /v[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
